// <auto-generated />
using System;
using FnBManagement.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FnBManagement.Web.Data.Migrations;

[DbContext(typeof(FnBManagementDbContext))]
[Migration("20260623000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FnBManagement.Web.Models.InventoryItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(160)
                    .HasColumnType("character varying(160)");

                b.Property<decimal>("QuantityInStock")
                    .HasPrecision(10, 2)
                    .HasColumnType("numeric(10,2)");

                b.Property<decimal>("ReorderLevel")
                    .HasPrecision(10, 2)
                    .HasColumnType("numeric(10,2)");

                b.Property<string>("Unit")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("character varying(40)");

                b.HasKey("Id");

                b.ToTable("InventoryItems", (string)null);
            });

        modelBuilder.Entity("FnBManagement.Web.Models.MenuItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Category")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("character varying(80)");

                b.Property<bool>("IsAvailable")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(true);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(160)
                    .HasColumnType("character varying(160)");

                b.Property<decimal>("Price")
                    .HasPrecision(10, 2)
                    .HasColumnType("numeric(10,2)");

                b.HasKey("Id");

                b.ToTable("MenuItems", (string)null);
            });

        modelBuilder.Entity("FnBManagement.Web.Models.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("OrderedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("Orders", (string)null);
            });

        modelBuilder.Entity("FnBManagement.Web.Models.OrderLineItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("MenuItemId")
                    .HasColumnType("integer");

                b.Property<string>("MenuItemName")
                    .IsRequired()
                    .HasMaxLength(160)
                    .HasColumnType("character varying(160)");

                b.Property<int>("OrderId")
                    .HasColumnType("integer");

                b.Property<int>("Quantity")
                    .HasColumnType("integer");

                b.Property<decimal>("UnitPrice")
                    .HasPrecision(10, 2)
                    .HasColumnType("numeric(10,2)");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.ToTable("OrderLines", (string)null);
            });

        modelBuilder.Entity("FnBManagement.Web.Models.OrderLineItem", b =>
            {
                b.HasOne("FnBManagement.Web.Models.Order", null)
                    .WithMany("Lines")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("FnBManagement.Web.Models.Order", b =>
            {
                b.Navigation("Lines");
            });
#pragma warning restore 612, 618
    }
}
